version: 2

sources:
  - name: gz_raw_data
    database: gz_raw_data
    schema: gz_raw_data
    tables:
      - name: raw_gz_sales
        identifier: raw_gz_sales
      - name: raw_gz_product
        identifier: raw_gz_product
      - name: raw_gz_ship
        identifier: raw_gz_ship
    loader: bigquery
    description: "Sources in BigQuery"


